#define APPLICATION_NAME @"app_name"
#define APPLICATION_ID @"app_id"
#define CONTRACT_ID @"contract_id"
#define P12_FILENAME @"p12_keystore_filename"
#define P12_PASSPHRASE @"p12_keystore_passphrase"
